# Análise e processamento de dados com Python 

## Introdução

A análise de dados é a transformação de números (i.e., os dados) desestruturados/desorganizados em informação útil. 

Esses dados são utilizados para encontrar padrões, tendências, etc. que ajudam a extrair informações úteis e que podem ajudar a solucionar problemas, tomar decisões, etc.

Analisar e processar dados é uma tarefa comum para engenheiros e cientistas. Normalmente, estes dados estão armazenados em arquivos texto, CSV, JSON, XML ou em bases de dados.

Utilizando Python, a análise e processamento de dados, como estatísticas, tendências, cálculos, etc., podem ser facilmente realizados para sintetizar as informações.

Para isso, o Python conta com técnicas e várias bibliotecas muito poderosas para o processamento de grandes quantidades de dados como:

+ **Programação Funcional**: preparação e exploração de dados.
+ **NumPy**: análise numérica e estatística.
+ **SciPy**: computação científica.
+ **Scikit-Learn**: aprendizado de máquina.
+ **Pandas**: manipulação, análise exploratória e visualização de dados.
+ **Matplotlib**: visualização de dados.
+ **Bokeh**: visualização de dados.

**IMPORTANTE**: As empresas tem percebido que analisar seus dados pode trazer grandes benefícios (redução de custos, aumento dos lucros, etc.) e sendo assim, o número de vagas para analistas e cientistas de dados só tem crescido.

Nesse tópico iremos estudar algumas ferramentas e bibliotecas utilizadas na análise e processamento de dados utilizando Python.

## Programação funcional

Como vimos na primeira aula, a linguagem Python suporta diversos paradigmas de programação. 

Dentre eles, um muito utilizado para o processamento de dados é o paradigma **Programação Funcional**.

Programação funcional é um paradigma que trata a computação como uma avaliação de funções matemáticas. Tais funções podem ser aplicadas em sequências de dados, que geralmente são listas.

As operações básicas do paradigma funcional são implementadas no Python pelas funções embutidas `lambda()`, `map()`, `filter()`, `reduce()` e `zip()`.

Essas operações são utilizadas para transformar, preparar e explorar estruturas de dados.

### Funções lambda

Em Python, `lambda` é uma função anônima composta apenas por expressões. As funções `lambda` podem ter apenas uma linha, e podem ser atribuídas a uma variável. Funções lambda são muito usadas em programação funcional.

Sintaxe:

```python
lambda <lista de variáveis>: <expressão>
```

**IMPORTANTE**: Uma função lambda pode receber qualquer número de argumentos, mas só pode ter uma expressão.

A sintaxe `lambda` permite que você crie definições de função de forma declarativa.

Exemplo #1:

In [9]:
resultado = (lambda a, b: a + b)(3, 4)

print(resultado)

7


Exemplo #2:

In [10]:
# Valor absoluto de um vetor 3D.
amp = lambda x, y, z: (x ** 2 + y ** 2 + z ** 2) ** 0.5

print(amp(1, 1, 1))
print(amp(3, 4, 5))

1.7320508075688772
7.0710678118654755


Exemplo #3:

Usando uma função anônima para criar uma função que sempre multiplica o parâmetro de entrada por um número definido previamente:

In [12]:
def myfunc(n):
    return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

22
33


**IMPORTANTE**: Funções lambda consomem menos recursos computacionais que as funções convencionais, porém são mais limitados.

### Mapeamento

O mapeamento consiste em aplicar uma função a todos os itens de uma sequência, gerando outra lista contendo os resultados e com o mesmo tamanho da lista inicial.

<img src="../figures/map_function.png" width="300" height="300">

Em Python, o mapeamento é implementado pela função `map()`, a qual retorna um objeto iterável que pode ser convertido em uma lista com a função embutida `list()`.

Exemplo #1:

In [26]:
# Importa apenas o log na base 10.
from math import log10

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

iterable = map(log10, nums)

# Aplicando o logaritmo na base 10.
resultado = list(iterable)

print(resultado)

Exemplo #2: Usando laço de repetição.

In [29]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

iterable = map(log10, nums)

for elemento in iterable:
    print(elemento)

0.0
0.3010299956639812
0.47712125471966244
0.6020599913279624
0.6989700043360189
0.7781512503836436
0.8450980400142568
0.9030899869919435
0.9542425094393249
1.0
1.0413926851582251
1.0791812460476249


Exemplo #3: 

Usando uma função anônima.

In [30]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Dividindo por 3.
resultado = list(map(lambda x: x / 3, nums))

print(resultado)

[0.3333333333333333, 0.6666666666666666, 1.0, 1.3333333333333333, 1.6666666666666667, 2.0, 2.3333333333333335, 2.6666666666666665, 3.0, 3.3333333333333335, 3.6666666666666665, 4.0]


### Filtragem

Na filtragem, uma função é aplicada em todos os elemento de uma sequência, se a função retornar um valor que seja avaliado como verdadeiro, o elemento original fará parte da sequência resultante.

<img src="../figures/filter_function.png" width="300" height="300">

Em Python, a filtragem é implementada pela função `filter()` e retorna um objetivo iterável que pode ser convertido em uma lista com a função embutida `list()`..

A função `filter()` aceita também funções lambda, além de funções convencionais.

Exemplo #1: Selecionando apenas os ímpares da lista.

In [60]:
# Selecionando apenas os ímpares da lista.
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

iterable = filter(lambda x: x % 2, nums)

resultado = list(iterable)

print(resultado)

[1, 3, 5, 7, 9, 11]


Exemplo #2: Selecionando apenas vogais.

In [61]:
# Alfabeto.
alfabeto = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'z']

# função que filtra as vogais.
def filtraVogais(letra):
    vogais = ['a', 'e', 'i', 'o', 'u']

    if(letra in vogais):
        return True
    else:
        return False

vogaisFiltradas = filter(filtraVogais, alfabeto)

print('As vogais filtradas são:')
for vogal in vogaisFiltradas:
    print(vogal)

As vogais filtradas são:
a
e
i
o
u


### Redução

Redução significa aplicar uma função que recebe dois parâmetros, nos dois primeiros elementos de uma sequência, aplicar novamente a função usando como parâmetros o resultado do primeiro par e o terceiro elemento da sequência, seguindo assim até o último elemento da sequência. O resultado final da redução é apenas um elemento.

<img src="../figures/reduce_function.png" width="300" height="300">

Em Python 3.7, a redução não faz parte das funções embutidas e é implementada pela função `reduce()` do módulo `functools`. Ela retorna um escalar, ou seja, um único valor que representa o resultado da redução. 

Exemplo #1: Somando todos os valores de uma lista.

In [76]:
from functools import reduce

nums = [0, 1, 2, 3]

resultado = reduce(lambda x, y: x + y, nums)

# Soma com reduce.
print('Resultado da soma com reduce:', resultado)

Resultado da soma com reduce: 6


Exemplo #2: Contatenando todos os valores de uma lista.

In [77]:
from functools import reduce

nums = ['ab', 'cde', 'f']

resultado = reduce(lambda x, y: x + y, nums)

# Concatenando com reduce.
print('Resultado da concatenação com reduce:', resultado)

Resultado da concatenação com reduce: abcdef


Exemplo #3: Calculando o fatorial com reduce.

In [78]:
from functools import reduce

# Calcula o fatorial de n.
def fatorial(n):
    return reduce(lambda x, y: x * y, range(1, n))

print('Fatorial:', fatorial(6))

Fatorial: 120


### Transposição


A transposição constroi novas sequência a partir de uma série de sequências originais, onde a primeira nova sequência contém o primeiro elemento de cada sequência original, a segunda nova sequência contém o segundo elemento de cada sequência original, até que alguma das sequências originais acabe.

<img src="../figures/zip_function.png" width="300" height="300">

A transposição é implementada em Python pela função embutida `zip()`. A função `zip()` recebe objetos iteráveis (e.g., listas, tuplas, dicionários, conjuntos, etc.), os agrega em tuplas e as retorna através de um objeto iterável. A função `zip()` sempre retorna um objeto iterável que pode ser convertido em uma lista com a função embutida `list()`.

Exemplo #1:

In [74]:
iteravel = zip(['a', 'b', 'c'], (1, 2, 3))

resultado = list(iteravel)

print(resultado)

[('a', 1), ('b', 2), ('c', 3)]


Em teoria, a função `zip()` deve ser usada com sequências de mesmo comprimento. Se as sequências tiverem comprimentos diferentes, a transposição resultante terá o mesmo comprimento que a sequência mais curta.

In [75]:
iteravel = zip(['a', 'b'], (1, 2, 3, 4, 5), {66:'A', 99:'2'})

resultado = list(iteravel)

print(list(resultado))

[('a', 1, 66), ('b', 2, 99)]


## List Comprehensions

Em computação, **list comprehension** é uma construção que equivale a uma notação matemática do tipo:

$$S = x^2 \forall \in \mathbb{N}, x \ge 20$$

Ou seja, $S$ é o conjunto formado por todos os valores de $x$ ao quadrado para todo $x$ no conjunto dos números naturais, apenas se $x$ for maior ou igual a 20.

Em suma, **list comprehension** é uma ferramenta muito poderosa, que cria uma nova lista com base em outra lista, através de uma única linha de código.

Sintaxe:

```python
lista = [ <expressão> for <referência> in <sequência> if <condição> ]
```

Exemplo #1: Exemplo onde apenas os números pares são elevados ao quadrado.

In [81]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Eleve os ímpares ao quadrado
list_comprehension = [ x**2 for x in nums if x % 2 ]

print(list_comprehension)

[1, 9, 25, 49, 81, 121]


**IMPORTANTE**: A utilização de **list comprehension** é mais eficiente do que usar as funções `map()` e `filter()` tanto em termos de uso de processador quanto em consumo de memória.

### Tarefas

1. <span style="color:blue">**QUIZ - Programação funcional e list comprehension**</span>: respondam ao questionário sobre programação funcional e list comprehension no MS teams, por favor. 
2. <span style="color:blue">**Laboratório #10 - Programação funcional e list comprehension**</span>: cliquem em um dos links abaixo para accessar os exercícios do laboratório #10.

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/zz4fap/python-programming/master?filepath=labs%2FLaboratorio10_Programacao_Funcional_e_List_Comprehension.ipynb)

[![Google Colab](https://badgen.net/badge/Launch/on%20Google%20Colab/blue?icon=terminal)](https://colab.research.google.com/github/zz4fap/python-programming/blob/master/labs/Laboratorio10_Programacao_Funcional_e_List_Comprehension.ipynb)

## NumPy: Uma biblioteca para computação científica

Numpy, ou numerical Python, é a principal biblioteca para computação científica em Python. Ela é utilizada para cálculos matemáticos avançados com alto nível de desempenho.

Numpy fornece uma interface com códigos compilados (e otimizados) em C
e Fortran, permitindo que as operações relativas a arrays sejam computadas
de maneira mais rápida e por isso, aumentando o desempenho.

O Numpy adiciona suporte para matrizes e arrays (i.e., vetores) multidimensionais grandes, junto com uma grande coleção de funções matemáticas de alto nível para operar nessas matrizes e arrays.

Se você já está familiarizado com o MATLAB, então você vai encontrar várias similaridades.

### Vetores e Matrizes

Vetores e matrizes (ou apenas arrays) NumPy são conjuntos de valores, todos do mesmo tipo e que podem ser indexados.

Podemos inicializar vetores e matrizes NumPy a partir de listas aninhadas e acessar seus elementos usando colchetes.

#### Exemplo: Criando um vetor

In [10]:
import numpy as np

a = np.array([1, 2, 3])   # Criando um vetor.
print(type(a))            # Imprime o tipo do vetor.
print(a.shape)            # Imprime a dimensão do vetor.
print(a.dtype)            # Imprime o tipo da ndarray.
print(a[0], a[1], a[2])   # Acessando valores específicos.
a[0] = 5                  # Altera o valor de um elemento do vetor.
print(a)                  # Imprime o conteúdo do vetor.

<class 'numpy.ndarray'>
(3,)
int32
1 2 3
[5 2 3]


#### Classe numpy.ndarray

Um objeto do tipo `ndarray` é um contêiner multidimensional genérico para dados **homogêneos**. 

Ele fornece operações aritméticas vetorizadas e recursos de transmissão sofisticados. 

Cada `ndarray` tem 2 atributos: **shape** (forma) e **dtype** (tipo). O atributo **shape** é uma tupla que fornece a dimensão do vetor ou matriz e **dtype** fornece o tipo de dados do vetor ou matriz.

#### Exemplo: Criando uma matriz

In [9]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]])    # Cria uma matriz 2x2.
print(b.shape)                     # Imprime as dimensões da matriz.
print(b.dtype)                     # Imprime o tipo da ndarray.
print(b[0, 0], b[0, 1], b[1, 0])   # Acessando valores específicos.
b[0, 0] = 5                        # Altera o valor de um elemento da matriz.
print(b)                           # Imprime o conteúdo da matriz.

(2, 3)
int32
1 2 4
[[5 2 3]
 [4 5 6]]


O NumPy também oferece muitas outras funções para criar vetores e matrizes:

In [153]:
print('Cria uma array com todos valores iguais a zero.')
a = np.zeros((2,2))           # Cria uma array com todos valores iguais a zero.
print(a)

print('\nCria uma array com todos valores iguais a um.')
b = np.ones((1,2))            # Cria uma array com todos valores iguais a um.
print(b)

print('\nCria uma array com valores constantes.')
c = np.full((2,2), 7)         # Cria uma array com valores constantes.
print(c)

print('\nCria uma matriz identidade 2x2.')
d = np.eye(2)                 # Cria uma matriz identidade 2x2.
print(d)

print('\nCria uma matriz com valores aleatórios uniformemente distribuidos.')
e = np.random.random((2,2))   # Cria uma matriz com valores aleatórios.
print(e)

print('\nCria uma matriz com valores aleatórios uniformemente distribuidos.')
e = np.random.rand(2,3)     # Cria uma matriz com valores aleatórios.
print(e)

print('\nCria uma matriz com valores inteiros aleatórios uniformemente distribuidos.')
e = np.random.randint(0,4,(2,2))     # Cria uma matriz com valores inteiros aleatórios.
print(e)

print('\nCria um vetor com valores aleatórios normalmente distribuidos.')
e = np.random.randn(1,4)     # Cria uma matriz com valores aleatórios.
print(e)

print('\nCria um vetor com um intervalo de valores.')
f = np.arange(0,10)
print(f)

print('\nCria um vetor com um intervalo de valores com passos de 2 em 2.')
g = np.arange(0,10,2)
print(g)

print('\nGera um número determinado de pontos uniformemente espaçados entre dois valores')
h = np.linspace(-3,3,3)
print(h)

Cria uma array com todos valores iguais a zero.
[[0. 0.]
 [0. 0.]]

Cria uma array com todos valores iguais a um.
[[1. 1.]]

Cria uma array com valores constantes.
[[7 7]
 [7 7]]

Cria uma matriz identidade 2x2.
[[1. 0.]
 [0. 1.]]

Cria uma matriz com valores aleatórios uniformemente distribuidos.
[[0.90576778 0.13973417]
 [0.1854783  0.0241876 ]]

Cria uma matriz com valores aleatórios uniformemente distribuidos.
[[0.45001369 0.91240073 0.73863148]
 [0.18576002 0.57225945 0.26488919]]

Cria uma matriz com valores inteiros aleatórios uniformemente distribuidos.
[[1 2]
 [3 1]]

Cria um vetor com valores aleatórios normalmente distribuidos.
[[ 0.26361493 -0.13794036  1.02236758 -1.07592653]]

Cria um vetor com um intervalo de valores.
[0 1 2 3 4 5 6 7 8 9]

Cria um vetor com um intervalo de valores com passos de 2 em 2.
[0 2 4 6 8]

Gera um número determinado de pontos uniformemente espaçados entre dois valores
[-3.  0.  3.]


Outros métodos para criação de arrays podem ser encontrados na documentação:
https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation

### Indexação de arrays

O NumPy oferece várias maneiras de indexar vetores e matrizes.

**Fatiamento**: similarmente ao que é feito com listas, arrays NumPy podem ser fatiadas. Como as arrays podem ser multidimensionais, você deve especificar uma **fatia** para cada dimensão dela:

In [55]:
# Cria uma matriz com dimensão 3x4.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('a: ',a)
print('a.shape:', a.shape)

# Acessa o elemento da primeira linha e segunda coluna.
b = a[0, 1]
print('\nb:', b)
print('b.shape:', b.shape)

# Fatiando para criar uma submatriz que consiste 
# nas 2 primeiras linhas (i.e., 0 e 1) e colunas 1 e 2 da matrix a.
# c será uma matriz de dimensão (2, 2):
c = a[:2, 1:3]
print('\nc:',c)
print('c.shape:',c.shape)

# Cria vetor com a segunda linha de a.
d = a[1, :]
print('\nc:',d)
print('d.shape:',d.shape)

# Uma fatia B de uma matriz A acessa os mesmos dados de A, 
# portanto, modificar B irá modificar a matriz original.
print('\na[0, 1]:', a[0, 1])   # Imprime o valor 2.
c[0, 0] = 77     # c[0, 0] acessa o mesmo elemento que a[0, 1]
print('a[0, 1]:', a[0, 1])   # Imprime o valor 77.

# Para criar uma subarray B independente de uma array A, usemos a função copy().
c = a.copy()[:2, 1:3]
print('\nc:',c)
print('c.shape:',c.shape)

print('\na[0, 1]:', a[0, 1])   # Imprime o valor 77.
c[0, 0] = 2     # c[0, 0] acessa o mesmo elemento que a[0, 1]
print('a[0, 1]:', a[0, 1])   # Imprime o valor 77.

a:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a.shape: (3, 4)

b: 2
b.shape: ()

c: [[2 3]
 [6 7]]
c.shape: (2, 2)

c: [5 6 7 8]
d.shape: (4,)

a[0, 1]: 2
a[0, 1]: 77

c: [[77  3]
 [ 6  7]]
c.shape: (2, 2)

a[0, 1]: 77
a[0, 1]: 77


### Indexando com filtragem condicional

Nós também podemos utilizar **filtragem condicional** para indexar arrays NumPy.

A **filtragem condicional** permite selecionar elementos arbitrários de uma array. 

Frequentemente, esse tipo de indexação é usado para selecionar os elementos de uma array que satisfazem alguma condição.

#### Exemplo #1:

In [103]:
a = np.arange(0,10)

print('Vetor a:',a)

# Encontra elementos que são maiores do que 4.
# A instrução abaixo retorna uma array numpy de valores Booleanos 
# com o mesmo formato do vetor a, onde cada índice informa se 
# esse elemento de a é maior do que 4.
indices = a > 4
print('indices:',indices)

# Usamos o vator booleano para construir uma array
# consistindo dos elementos que correspondem aos 
# valores verdadeiros do vetor indices.
print('a[indices]:', a[indices])

# Podemos fazer tudo isso em uma única e concisa declaração.
print('a[a > 4]:', a[a > 4])

Vetor a: [0 1 2 3 4 5 6 7 8 9]
indices: [False False False False False  True  True  True  True  True]
a[indices]: [5 6 7 8 9]
a[a > 4]: [5 6 7 8 9]


#### Exemplo #2:

In [108]:
a = np.array([1, 2, 1, 3, 2])

indices = a == 2

b = a[indices]

print('a:',a)
print('indices:',indices)
print('a[indices]:',b)

a: [1 2 1 3 2]
indices: [False  True False False  True]
a[indices]: [2 2]


### Tipos dos dados

Cada array NumPy é um conjunto de elementos do mesmo tipo. O NumPy fornece um grande conjunto de tipos de dados que podemos usar para construir arrays. 

O Numpy infere o tipo de dados quando criamos uma array, mas as funções que constroem arrays geralmente também incluem um parâmetro opcional para especificar explicitamente o tipo dos dados.

#### Exemplos

In [44]:
x = np.array([1, 2])   # Deixamos o NumPy inferir o tipo dos dados.
print(x.dtype)         # Imprime "int64"

x = np.array([1.0, 2.0])   # O NumPy infere o tipo dos dados.
print(x.dtype)             # Imprime "float64"

x = np.array([1, 2], dtype=np.int64)   # Forçando um tipo específico.
print(x.dtype)                         # Imprime "int64"

int32
float64
int64


### Redimensionando Arrays

Nós podemos mudar as dimensões das arrays criadas com o método `reshape`.

In [52]:
a = np.array([1,2,3,4])
print('a.shape:',a.shape)

b = a.reshape(2,2)
print('b.shape:',b.shape)

c = a.reshape(4,1)
print('c.shape:',c.shape)

d = c.reshape(1,4)
print('c.shape:',d.shape)

a.shape: (4,)
b.shape: (2, 2)
c.shape: (4, 1)
c.shape: (1, 4)


### Cálculos com arrays

O NumPy é conhecido por sua velocidade ao realizar cálculos complexos em grandes arrays multidimensionais. 

Funções matemáticas básicas operam elemento a elemento das arrays e estão disponíveis através de sobrecarga de operadores e como funções no NumPy.

Em seguida, veremos como realizar esses cálculos com o NumPy.

In [68]:
# Criando 2 matrizes 2x2.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# -------- Adição --------
y = a + b # sobrecarga do operador +
print('----> Exemplo #1: Adição de matrizes.')
print('y = a + b:',y)

y = np.add(a,b) # função add()
print('y = np.add(a,b):',y)

# -------- Subtração --------
y = a - b # sobrecarga do operador -
print('\n----> Exemplo #2: Subtração de matrizes.')
print('y = a - b:',y)

y = np.subtract(a,b) # função subtract()
print('y = np.subtract(a,b):',y)

# -------- Multiplicação --------
y = a * b # sobrecarga do operador *
print('\n----> Exemplo #3: Multiplicação de matrizes.')
print('y = a * b:',y)

y = np.multiply(a,b) # função multiply()
print('y = np.multiply(a,b):',y)

# -------- Divisão --------
y = a / b # sobrecarga do operador /
print('\n----> Exemplo #4: Divisão de matrizes.')
print('y = a / b:',y)

y = np.divide(a,b) # função divide()
print('y = np.divide(a,b):',y)

----> Exemplo #1: Adição de matrizes.
y = a + b: [[ 6  8]
 [10 12]]
y = np.add(a,b): [[ 6  8]
 [10 12]]

----> Exemplo #2: Subtração de matrizes.
y = a - b: [[-4 -4]
 [-4 -4]]
y = np.subtract(a,b): [[-4 -4]
 [-4 -4]]

----> Exemplo #3: Multiplicação de matrizes.
y = a * b: [[ 5 12]
 [21 32]]
y = np.multiply(a,b): [[ 5 12]
 [21 32]]

----> Exemplo #4: Divisão de matrizes.
y = a / b: [[0.2        0.33333333]
 [0.42857143 0.5       ]]
y = np.divide(a,b): [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Existem algumas funções embutidas disponíveis no NumPy para calcular valores como média, desvio padrão, variância e outros.

|    Operação   |   Função  |
|:-------------:|:---------:|
|      Soma     |  np.sum() |
| Raiz quadrada | np.sqrt() |
|     Média     | np.mean() |
|   Variância   |  np.var() |
| Desvio Padrão |  np.std() |

In [79]:
a = np.array([1, 2, 3])
b = np.array([[1,2], [3,4]])

x = np.sum(a)
print('np.sum(a):', x)

y = np.sum(b)
print('np.sum(b):', y)

x = np.sqrt(a)
print('np.sqrt(a):',x)

x = np.mean(a)
print('np.mean(a):',x)

x = np.var(a)
print('np.var(a):',x)

x = np.std(a)
print('np.std(a):',x)

np.sum(a): 6
np.sum(b): 10
np.sqrt(a): [1.         1.41421356 1.73205081]
np.mean(a): 2.0
np.var(a): 0.6666666666666666
np.std(a): 0.816496580927726


Observe que, ao contrário do MATLAB, o operador `*` é uma multiplicação elemento-a-elemento, não uma multiplicação de matrizes. 

Em vez disso, usamos a função `dot()` para calcular produtos internos de vetores, para multiplicar um vetor por uma matriz e para multiplicar matrizes. 

`dot()` está disponível como uma função do módulo NumPy e como um método da classe `numpy.ndarray`:

In [81]:
# Cria 2 matrizes 2x2.
x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])

# Cria 2 vetores.
v = np.array([9, 10])
w = np.array([11, 12])

# Produto interno dos vetores v e w.
print('Produto interno entre os vetores v e w.')
print(v.dot(w))
print(np.dot(v, w))

# Produto interno entre uma matriz e um vetor.
print('\nProduto interno entre a matriz x e o vetor v')
print(x.dot(v))
print(np.dot(x, v))

# Produto interno entre matrizes.
print('\nProduto interno entre a matriz x e a matriz y')
print(x.dot(y))
print(np.dot(x, y))

Produto interno entre os vetores v e w.
219
219

Produto interno entre a matriz x e o vetor v
[29 67]
[29 67]

Produto interno entre a matriz x e a matriz y
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Para realizar a transposição de uma matriz, basta usar o atributo `T` de um objeto do tipo `numpy.ndarray`:

In [95]:
# Criando uma matriz 2x2.
x = np.array([[1,2], [3,4]])
print('Exemplo #1: transposição de uma matrix 2x2:')
print('x.shape:',x.shape)
print('x:',x)
print('x.T:',x.T)

# Criando um vetor coluna com dimensão 3x1.
v = np.array([1,2,3]).reshape(3,1)
print('\nExemplo #2: transposição de um vetor 3x1:')
print('v.shape:',v.shape)
print('v:',v)
print('v.T',v.T)

Exemplo #1: transposição de uma matrix 2x2:
x.shape: (2, 2)
x: [[1 2]
 [3 4]]
x.T: [[1 3]
 [2 4]]

Exemplo #2: transposição de um vetor 3x1:
v.shape: (3, 1)
v: [[1]
 [2]
 [3]]
v.T [[1 2 3]]


## Adicionando e removendo elementos de uma array

Existem algumas funções para adicionar e remover elementos de arrays:

|           Operador           |             Função            |
|:----------------------------:|:-----------------------------:|
|        np.append(array, values, axis=None)        | Acrescenta elementos ao final da array. |
| np.insert(array, obj, values, axis=None) |   Insire elementos ao longo do eixo fornecido antes dos índices fornecidos.  |
|    np.delete(array, obj, axis=None)   | Retorna uma array com submatrizes ao longo do eixo excluído.|

In [148]:
# Criando 2 vetores.
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[1,2],[3,4]])

# Acrescentando elementos a uma array.
print('Acrescentando elementos a uma array.')
d = np.append(a, b)
print('d:',d)

# Inserindo elementos em uma array.
print('\nInserindo elementos em uma array.')
e = np.insert(a, 2, 77)
print('e:',e)

f = np.insert(c, 1, 77, axis=0)
print('f:',f)

g = np.insert(c, 1, 77, axis=1)
print('g:',g)

print('\nDeletando elementos de uma array.')
h = np.delete(a, 0)
print('h:',h)

i = np.delete(a, [0, 1])
print('i:',i)

j = np.delete(c, 0, axis=0)
print('j:',j)

l = np.delete(c, 0, axis=1)
print('l:',l)

Acrescentando elementos a uma array.
d: [0 1 2 3 4 5 6 7]

Inserindo elementos em uma array.
e: [ 0  1 77  2  3]
f: [[ 1  2]
 [77 77]
 [ 3  4]]
g: [[ 1 77  2]
 [ 3 77  4]]

Deletando elementos de uma array.
h: [1 2 3]
i: [2 3]
j: [[3 4]]
l: [[2]
 [4]]


### Conclusão

Esta breve visão geral abordou muitas das coisas importantes que precisamos saber sobre o NumPy, mas está longe de ser completa. 

Confiram o link seguinte para descobrirem muito mais sobre o NumPy: http://docs.scipy.org/doc/numpy/reference/

### Tarefas

1. <span style="color:blue">**QUIZ - NumPy**</span>: respondam ao questionário sobre a biblioteca NumPy no MS teams, por favor. 
2. <span style="color:blue">**Laboratório #10 - NumPy**</span>: cliquem em um dos links abaixo para accessar os exercícios do laboratório #10.

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/zz4fap/python-programming/master?filepath=labs%2FLaboratorio10_NumPy.ipynb)

[![Google Colab](https://badgen.net/badge/Launch/on%20Google%20Colab/blue?icon=terminal)](https://colab.research.google.com/github/zz4fap/python-programming/blob/master/labs/Laboratorio10_NumPy.ipynb)

## Computação científica com SciPy

## Manipulação e análise exploratória de dados com Pandas


## Visualização de dados com Matplotlib


## Visualização de dados com Bokeh